#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x bspwmrc > /dev/null || /home/gor/.config/bspwm/./bspwmrc & 
pgrep -x focusborder > /dev/null || /home/gor/.config/bspwm/./focusborder &

bspc monitor -d 1 2 3 4 5

bspc config border_width         5
bspc config window_gap           0

bspc config normal_border_color  '#ffffff'
bspc config focused_border_color '#040ab3' # '#0007b8' # '#040ab3' # '#770000'

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true
bspc config focus_follows_pointer true

xset r rate 300 50 &

bspc rule -a zathura state=tiling follow=on
bspc rule -a Screenkey manage=off
#
# herbe "Check your notes" && $TERMINAL -e vi ~/zeta/.notes
herbewarning "TODO EXERCISE LOGIC: ExercisesBooklet.pdf" && zathura /home/gor/ExercisesBooklet.pdf
